# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3300d293df531f9f003624ab0adb1bcfbf4bdf899a756191ec794ac289e2e0427702a1f09e8162ce0938521b4da0e0e753b1b8d9ce6fe4954ccaaf2c6e6bc503

test:
  secret_key_base: 4c938b5cb393be261a2bcb7dac5b88289cd275240dae341d1dc27bab9ff2caa33c7ff7473195a6cb672e09842e23ab756d41716acf67dd4c0e5402a2aac70128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
